"""Add performance indexes for candidates

Revision ID: 90171df8dd03
Revises: 633e0e4fb3df
Create Date: 2026-04-04 00:28:48.060478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90171df8dd03'
down_revision: Union[str, None] = '633e0e4fb3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_candidates_created_by_created_at', 'candidates', ['created_by', sa.text('created_at DESC')])
    op.create_index('ix_candidates_created_by_status', 'candidates', ['created_by', 'ingestion_status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_created_by_status', table_name='candidates')
    op.drop_index('ix_candidates_created_by_created_at', table_name='candidates')
    # ### end Alembic commands ###
